name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: "iamgacarvalho/dmc-reviews-aggregate-apps-santander"
  DOCKER_TAG: "1.0.0"

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Login no DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.COMPASS_USER_DOCKERHUB }}
          password: ${{ secrets.COMPASS_PASSWORD_DOCKERHUB }}

      # Construção da imagem
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

      # Push da imagem para o DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
